[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install"
 
[deploy]
startCommand = "cd backend && node app.js"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE" 