[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && node app.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure" 